# Generated by Django 6.0.3 on 2026-03-14 09:10

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Shop Name')),
                ('facebook_page_url', models.URLField(unique=True, verbose_name='Facebook Page URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trial_ends_at', models.DateTimeField(default=store.models.get_trial_end_date)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid Subscriber')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
