# Generated by Django 6.0.3 on 2026-03-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_shop_address_shop_facebook_link_shop_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='facebook_link',
        ),
        migrations.AddField(
            model_name='shop',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='steadfast_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='steadfast_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
