# Generated by Django 6.0.3 on 2026-03-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_shop_facebook_link_shop_sms_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='steadfast_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
