# Generated by Django 6.0.3 on 2026-03-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_steadfast_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='sms_balance',
            field=models.IntegerField(default=50),
        ),
    ]
