# Generated by Django 6.0.3 on 2026-03-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='subscription_plan',
            field=models.CharField(choices=[('Free', 'Free (Trial)'), ('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Free', max_length=20),
        ),
    ]
