# Generated by Django 6.0.3 on 2026-03-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_shop_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='facebook_page_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
