# Generated by Django 6.0.3 on 2026-03-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_shop_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_store_id', models.CharField(blank=True, help_text='Store ID or App Key', max_length=255, null=True)),
                ('payment_secret_key', models.CharField(blank=True, help_text='Store Password or App Secret', max_length=255, null=True)),
                ('is_payment_live', models.BooleanField(default=False, help_text='Check to make payments live')),
                ('sms_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_sender_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
