# Generated by Django 6.0.5 on 2026-05-30 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_use_pos', models.BooleanField(default=True, help_text='Can process sales in POS')),
                ('can_manage_products', models.BooleanField(default=False, help_text='Can add, edit or delete products')),
                ('can_manage_orders', models.BooleanField(default=False, help_text='Can change order status & delete')),
                ('can_manage_customers', models.BooleanField(default=False, help_text='Can view customer details')),
                ('can_view_reports', models.BooleanField(default=False, help_text='Can view revenue & profit reports')),
                ('can_manage_settings', models.BooleanField(default=False, help_text='Can access shop settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='store.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
