# Generated by Django 6.0.5 on 2026-05-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_partner',
            field=models.CharField(blank=True, help_text='e.g., Steadfast, Pathao, RedX', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='pathao_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='pathao_store_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='redx_access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
