# Generated by Django 6.0.1 on 2026-06-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_shop_valid_until_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersetting',
            name='sms_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
