# Generated by Django 6.0.1 on 2026-06-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_mastersetting_sms_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_sms_active',
            field=models.BooleanField(default=True, help_text='Turn on/off SMS sending'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sms_balance',
            field=models.IntegerField(default=0),
        ),
    ]
