# Generated by Django 6.0.1 on 2026-06-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_shop_is_sms_active_alter_shop_sms_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='privacy_policy',
            field=models.TextField(blank=True, help_text='আপনার স্টোরের প্রাইভেসি পলিসি লিখুন', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='return_policy',
            field=models.TextField(blank=True, help_text='আপনার স্টোরের রিটার্ন পলিসি লিখুন', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
